default:
  username: "admin"
  password: "admin"
  enable_secret: ""

overrides:
  arista-leaf-01:
    username: admin
    password: admin
    enable_secret: ""
  arista-leaf-02:
    username: admin
    password: admin
    enable_secret: ""
