arista_eos:
  filename: EOS64-4.32.5.1M.bin
  path: firmware/
  md5: "EOS64-4.32.5.1M.bin.md5"
  reload_times: ["12:30", "20:30"]
cisco_ios:
  filename: somefile.bin
  path: firmware/
  md5: "another_md5"
  reload_times: ["12:30", "20:30"]